const ImageStore = {
	images: [
		{
			id: 1,
			path: "../datasets/dataset1/SKU1/111.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU1",
		},
		{
			id: 2,
			path: "../datasets/dataset1/SKU1/222.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU1",
		},
		{
			id: 3,
			path: "../datasets/dataset1/SKU1/333.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU1",
		},
		{
			id: 4,
			path: "../datasets/dataset1/SKU1/444.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU1",
		},
		{
			id: 5,
			path: "../datasets/dataset1/SKU1/555.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU1",
		},
		{
			id: 6,
			path: "../datasets/dataset1/SKU1/666.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU1",
		},
		{
			id: 7,
			path: "../datasets/dataset1/SKU2/111.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU2",
		},
		{
			id: 8,
			path: "../datasets/dataset1/SKU2/222.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU2",
		},
		{
			id: 9,
			path: "../datasets/dataset1/SKU2/333.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU2",
		},
		{
			id: 10,
			path: "../datasets/dataset1/SKU2/444.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU2",
		},
		{
			id: 11,
			path: "../datasets/dataset1/SKU2/555.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU2",
		},
		{
			id: 12,
			path: "../datasets/dataset1/SKU2/666.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset1",
			SKU: "SKU2",
		},
		{
			id: 13,
			path: "../datasets/dataset2/SKU3/111.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU3",
		},
		{
			id: 14,
			path: "../datasets/dataset2/SKU3/222.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU3",
		},
		{
			id: 15,
			path: "../datasets/dataset2/SKU3/333.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU3",
		},
		{
			id: 16,
			path: "../datasets/dataset2/SKU3/444.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU3",
		},
		{
			id: 17,
			path: "../datasets/dataset2/SKU3/555.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU3",
		},
		{
			id: 18,
			path: "../datasets/dataset2/SKU3/666.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU3",
		},
		{
			id: 19,
			path: "../datasets/dataset2/SKU4/111.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU4",
		},
		{
			id: 20,
			path: "../datasets/dataset2/SKU4/222.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU4",
		},
		{
			id: 21,
			path: "../datasets/dataset2/SKU4/333.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU4",
		},
		{
			id: 22,
			path: "../datasets/dataset2/SKU4/444.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU4",
		},
		{
			id: 23,
			path: "../datasets/dataset2/SKU4/555.jpg",
			confidence: false,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU4",
		},
		{
			id: 24,
			path: "../datasets/dataset2/SKU4/666.jpg",
			confidence: true,
			image_info: {
				width: 320,
				height: 180,
				blur: false,
				motion_blur: false,
			},
			dataset: "dataset2",
			SKU: "SKU4",
		},
	],
};

export default ImageStore;
